### ISSUE TITLE
live orchestration of truechain-engine

### ISSUE THREAD

**Issue by arcolife** [truechain/truechain-consensus-core#26]
Use capabilities of `cli` for controlling truechain-engine and make it run as a daemon.

This really should be a `geth` like integration, but for fastchain. For example: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options  

Currently feasible options:

For client (currently simulated with the binary :

```
Usage of ./bin/linux/truechain-engine:
  -numquest int
    	number of requests (default 10)
```

For server, something like:

```
..
dump
checkview/sequence
...
```

..basically all things pbft, maybe specific to this tunable (as found under `config.yaml`):

```yaml
---
basePort: 49500
grpcBasePort: 10000
maxFail: 1
bftcommittee:
  actualDelta: 0
  csize: 0
  delta: 1
  lambda: 1
  tbft: 1
  th: 10
  timeout: 300
slowchain:
  csize: 0
testbedconfig:
  clientID: 5
  initServerID: 4
  requests:
    batchSize: 32
    max: 256
  threadingEnabled: true
  total: 5
```
